### ISSUE TITLE
Various SPB issues in the tracker

### ISSUE THREAD

**Issue by MinaAngura** [olji/Reflux#13]
1) Not all SPBs are showing up as Unlocked correctly.  I'm not sure why.

2) Game is detecting SPB charts that are not currently accessible in Infinitas.  We need to find a way to limit the SPB data inserted into the TSV to only charts currently available.

**Comment by justOkapi** [comment]
Re: 2, I compiled a list of the songs with Beginners currently accessible, in case we wanted to tackle it like we did for encodingfixes and customtypes.  I'm not seeing a pattern to how the songs with Beginner charts are flagging in the songlist.  I'm not sure if I'm overlooking something or if we just need more eyes on it but I'm kind of at a roadblock with how to move forward on it due to skill issue.

**Comment by AllenSeitz** [comment]
2. It's not just charts with a non-zero rating? Throughout IIDX's history they've aggressively cut beginner charts in order to keep the beginner folder fresh and small. And AFAIK the tool they use is to rate the cut beginner charts 0. I even have a tool that scans all the charts in a game and identifies which charts exist in the chart files but have a 0 rating in he database. (And it finds mostly beginner charts that have been pruned over the years.)

**Comment by AllenSeitz** [comment]
1. I'm not sure if I am reading the code in tracker.cs correctly. But the following suspicious line appears on lines 86 and 121.

> if (i > (int)Difficulty.SPB && i < (int)Difficulty.SPL)

Since i is [0..9] inclusive and Difficulty.SPB is 0, wouldn't that skip these blocks of code for SPB? Those two blocks of code handle bit cost data.

**Comment by justOkapi** [comment]
Yes that is what that line does. Otherwise it causes weird offset issues whenever SPB and/or SPL exist.  That line has existed forever, I just changed it around for the new stuff.  And in my test TSV, the cut beginner charts are rated correctly, so it's an MDB thing similar to how it's currently handled in AC I guess?  Idk.

**Comment by MinaAngura** [comment]
Fixed as of 1.14.
