### ISSUE TITLE
Tracker believes song is passed if Early Quit with >80% on the Groove Gauge

### ISSUE THREAD

**Issue by justOkapi** [olji/Reflux#4]
I believe this is an issue with how we're gauging Clear/Fail with gauges up to Normal.

**Comment by olji** [comment]
The software should only fetch the lamp value that it reads from the playdata as a signifier if it's clearing or not and don't really do anything with gauge percent except save it.
The output to the marquee text file only writes "<title> clear!" if the lamp is not F, other than that I don't think it has any special behaviour depending on clear state even.

However in cases where the play data doesn't exist because it disables score saving (H-RAN, ANY KEY and similar) then it fetches the chart using the offset for currently playing song instead and blindly set an AC lamp without looking at gauge at all, which have to be addressed. Is this what you observed?

**Comment by justOkapi** [comment]
It's possible that's the case, yes.  It's not a *huge* issue so it's kind of on the backburner but I'll try to reproduce it with various circumstances and report back.
